#!/usr/bin/env python3
"""Interactive CLI wizard for guided ComfyUI Engine configuration and setup.

Provides step-by-step configuration, validation, and one-command deployment
for Arch Linux systems. Supports both interactive TUI and headless modes.
"""

import argparse
import asyncio
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# Rich for beautiful terminal UI
try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm, IntPrompt, Prompt
    from rich.table import Table
    from rich.text import Text
    from rich.progress import Progress, SpinnerColumn, TextColumn

    HAS_RICH = True
except ImportError:
    HAS_RICH = False


console = Console() if HAS_RICH else None


@dataclass
class EngineConfig:
    """Complete engine configuration generated by the wizard."""

    # ComfyUI Server
    comfyui_host: str = "127.0.0.1"
    comfyui_port: int = 8188
    comfyui_api_prefix: str = "/api"

    # Generation Settings
    default_width: int = 512
    default_height: int = 512
    default_steps: int = 20
    default_cfg: float = 7.0
    default_sampler: str = "euler_ancestral"
    default_scheduler: str = "normal"

    # Performance
    max_concurrent_jobs: int = 4
    queue_poll_interval: float = 1.0
    request_timeout: float = 300.0
    retry_attempts: int = 3
    retry_backoff: float = 2.0

    # Output
    output_dir: str = "output_models"
    save_metadata: bool = True
    metadata_format: str = "json"  # json, yaml, or both
    git_enabled: bool = True
    git_auto_commit: bool = True

    # Advanced Features
    mlflow_enabled: bool = False
    mlflow_tracking_uri: str = ""
    redis_enabled: bool = False
    redis_url: str = "redis://localhost:6379/0"
    metrics_enabled: bool = False
    metrics_port: int = 9090
    websocket_enabled: bool = True
    checkpoint_enabled: bool = True

    # Paths
    prompts_config: str = "config/prompts.yaml"
    log_dir: str = "logs"
    session_dir: str = ".sessions"

    # Systemd
    systemd_user: bool = True
    systemd_instances: int = 1

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    def to_env_file(self) -> str:
        """Generate .env file content."""
        lines = ["# ComfyUI Engine Configuration", "# Generated by setup wizard", ""]
        for key, value in self.to_dict().items():
            env_key = f"ENGINE_{key.upper()}"
            if isinstance(value, bool):
                value = str(value).lower()
            elif isinstance(value, list):
                value = json.dumps(value)
            lines.append(f"{env_key}={value}")
        return "\n".join(lines)


class WizardStep:
    """Base class for wizard steps."""

    def __init__(self, name: str, description: str):
        self.name = name
        self.description = description

    async def run(self, config: EngineConfig) -> EngineConfig:
        raise NotImplementedError


class WelcomeStep(WizardStep):
    """Welcome and system detection."""

    def __init__(self):
        super().__init__("Welcome", "System detection and welcome")

    async def run(self, config: EngineConfig) -> EngineConfig:
        if console:
            console.print(
                Panel.fit(
                    "[bold blue]ComfyUI Engine Setup Wizard[/bold blue]\n\n"
                    "This wizard will guide you through configuring the ComfyUI Engine\n"
                    "for optimal performance on your system.",
                    title="Welcome",
                    border_style="blue",
                )
            )

            # Detect system
            system = self._detect_system()
            console.print(f"\n[green]Detected OS:[/green] {system['os']}")
            console.print(f"[green]Python:[/green] {system['python']}")
            console.print(f"[green]Architecture:[/green] {system['arch']}")

            if system["os"] == "Linux":
                distro = system.get("distro", "Unknown")
                console.print(f"[green]Distribution:[/green] {distro}")
                if "arch" in distro.lower():
                    console.print("[cyan]✓ Arch Linux detected - full systemd support available[/cyan]")

            console.print()
            Confirm.ask("Press Enter to continue", default=True)

        return config

    def _detect_system(self) -> dict[str, str]:
        """Detect system information."""
        info = {
            "os": sys.platform,
            "python": f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}",
            "arch": os.uname().machine if hasattr(os, "uname") else "unknown",
        }

        if sys.platform == "linux":
            try:
                with open("/etc/os-release") as f:
                    for line in f:
                        if line.startswith("PRETTY_NAME="):
                            info["distro"] = line.split("=")[1].strip().strip('"')
                            break
            except Exception:
                pass

        return info


class ServerConfigStep(WizardStep):
    """Configure ComfyUI server connection."""

    def __init__(self):
        super().__init__("Server", "ComfyUI server configuration")

    async def run(self, config: EngineConfig) -> EngineConfig:
        if console:
            console.print(Panel("[bold]ComfyUI Server Configuration[/bold]", border_style="green"))

            config.comfyui_host = Prompt.ask(
                "Server host",
                default=config.comfyui_host,
            )
            config.comfyui_port = IntPrompt.ask(
                "Server port",
                default=config.comfyui_port,
            )

            # Test connection
            if Confirm.ask("Test connection to ComfyUI server?", default=True):
                await self._test_connection(config)

        return config

    async def _test_connection(self, config: EngineConfig) -> None:
        """Test connection to ComfyUI server."""
        import aiohttp

        url = f"http://{config.comfyui_host}:{config.comfyui_port}{config.comfyui_api_prefix}/system_stats"

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
        ) as progress:
            task = progress.add_task("Testing connection...", total=None)

            try:
                async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=5)) as session, session.get(
                    url
                ) as response:
                    if response.status == 200:
                        data = await response.json()
                        progress.update(task, description="[green]✓ Connection successful![/green]")
                        if console:
                            console.print(f"[green]Server info:[/green] {data}")
                    else:
                        progress.update(task, description=f"[red]✗ Server returned {response.status}[/red]")
            except Exception as e:
                progress.update(task, description=f"[red]✗ Connection failed: {e}[/red]")
                if console:
                    console.print("[yellow]You can continue setup and fix the connection later.[/yellow]")


class GenerationDefaultsStep(WizardStep):
    """Configure default generation parameters."""

    def __init__(self):
        super().__init__("Generation", "Default generation settings")

    async def run(self, config: EngineConfig) -> EngineConfig:
        if console:
            console.print(Panel("[bold]Default Generation Settings[/bold]", border_style="green"))

            config.default_width = IntPrompt.ask(
                "Default image width",
                default=config.default_width,
            )
            config.default_height = IntPrompt.ask(
                "Default image height",
                default=config.default_height,
            )
            config.default_steps = IntPrompt.ask(
                "Default sampling steps",
                default=config.default_steps,
            )
            config.default_cfg = float(
                Prompt.ask(
                    "Default CFG scale",
                    default=str(config.default_cfg),
                )
            )

            # Sampler selection
            samplers = [
                "euler",
                "euler_ancestral",
                "heun",
                "dpm_2",
                "dpm_2_ancestral",
                "lms",
                "dpm_fast",
                "dpm_adaptive",
                "dpmpp_2s",
                "dpmpp_sde",
                "dpmpp_2m",
                "dpmpp_2m_sde",
                "ddim",
                "uni_pc",
                "uni_pc_bh2",
            ]

            console.print("\nAvailable samplers:")
            for i, sampler in enumerate(samplers, 1):
                marker = " ← default" if sampler == config.default_sampler else ""
                console.print(f"  {i}. {sampler}{marker}")

            choice = IntPrompt.ask(
                "Select default sampler (number)",
                default=samplers.index(config.default_sampler) + 1,
            )
            if 1 <= choice <= len(samplers):
                config.default_sampler = samplers[choice - 1]

        return config


class PerformanceStep(WizardStep):
    """Configure performance and concurrency settings."""

    def __init__(self):
        super().__init__("Performance", "Performance tuning")

    async def run(self, config: EngineConfig) -> EngineConfig:
        if console:
            console.print(Panel("[bold]Performance Configuration[/bold]", border_style="yellow"))

            # Detect CPU cores for default recommendation
            cpu_count = os.cpu_count() or 4
            recommended_concurrent = max(1, cpu_count // 2)

            console.print(f"[dim]Detected {cpu_count} CPU cores[/dim]")

            config.max_concurrent_jobs = IntPrompt.ask(
                "Max concurrent generation jobs",
                default=recommended_concurrent,
            )
            config.queue_poll_interval = float(
                Prompt.ask(
                    "Queue poll interval (seconds)",
                    default=str(config.queue_poll_interval),
                )
            )
            config.retry_attempts = IntPrompt.ask(
                "Retry attempts on failure",
                default=config.retry_attempts,
            )

            if console:
                console.print("\n[cyan]Recommended settings for your hardware:[/cyan]")
                table = Table(show_header=True, header_style="bold")
                table.add_column("Setting")
                table.add_column("Value")
                table.add_column("Description")

                table.add_row(
                    "Concurrent jobs",
                    str(config.max_concurrent_jobs),
                    "Based on CPU core count",
                )
                table.add_row(
                    "Poll interval",
                    f"{config.queue_poll_interval}s",
                    "Balance between responsiveness and CPU usage",
                )

                console.print(table)

        return config


class AdvancedFeaturesStep(WizardStep):
    """Configure advanced features."""

    def __init__(self):
        super().__init__("Advanced", "Advanced features")

    async def run(self, config: EngineConfig) -> EngineConfig:
        if console:
            console.print(Panel("[bold]Advanced Features[/bold]", border_style="magenta"))

            # MLflow
            config.mlflow_enabled = Confirm.ask(
                "Enable MLflow experiment tracking?",
                default=config.mlflow_enabled,
            )
            if config.mlflow_enabled:
                config.mlflow_tracking_uri = Prompt.ask(
                    "MLflow tracking URI (leave empty for local)",
                    default=config.mlflow_tracking_uri,
                )

            # Redis
            config.redis_enabled = Confirm.ask(
                "Enable Redis distributed queue?",
                default=config.redis_enabled,
            )
            if config.redis_enabled:
                config.redis_url = Prompt.ask(
                    "Redis URL",
                    default=config.redis_url,
                )

            # Metrics
            config.metrics_enabled = Confirm.ask(
                "Enable Prometheus metrics endpoint?",
                default=config.metrics_enabled,
            )
            if config.metrics_enabled:
                config.metrics_port = IntPrompt.ask(
                    "Metrics port",
                    default=config.metrics_port,
                )

            # Other features
            config.websocket_enabled = Confirm.ask(
                "Enable WebSocket real-time updates?",
                default=config.websocket_enabled,
            )
            config.checkpoint_enabled = Confirm.ask(
                "Enable checkpoint/resume for batches?",
                default=config.checkpoint_enabled,
            )

            # Git
            config.git_enabled = Confirm.ask(
                "Enable Git integration for outputs?",
                default=config.git_enabled,
            )
            if config.git_enabled:
                config.git_auto_commit = Confirm.ask(
                    "Auto-commit on each generation?",
                    default=config.git_auto_commit,
                )

        return config


class SystemdStep(WizardStep):
    """Configure systemd service for Arch Linux."""

    def __init__(self):
        super().__init__("Systemd", "Systemd service configuration")

    async def run(self, config: EngineConfig) -> EngineConfig:
        if sys.platform != "linux":
            if console:
                console.print("[yellow]Systemd configuration skipped (not Linux)[/yellow]")
            return config

        if console:
            console.print(Panel("[bold]Systemd Service Setup[/bold]", border_style="cyan"))

            config.systemd_user = Confirm.ask(
                "Install as user service (not system-wide)?",
                default=config.systemd_user,
            )
            config.systemd_instances = IntPrompt.ask(
                "Number of engine instances",
                default=config.systemd_instances,
            )

            if Confirm.ask("Install systemd service now?", default=False):
                await self._install_systemd(config)

        return config

    async def _install_systemd(self, config: EngineConfig) -> None:
        """Install systemd service files."""
        try:
            service_dir = (
                Path.home() / ".config" / "systemd" / "user" if config.systemd_user else Path("/etc/systemd/system")
            )
            service_dir.mkdir(parents=True, exist_ok=True)

            # Copy service template
            source = Path("systemd/comfyui-engine@.service")
            if source.exists():
                dest = service_dir / "comfyui-engine@.service"
                shutil.copy2(source, dest)

                if console:
                    console.print(f"[green]✓ Installed service template to {dest}[/green]")
                    console.print("\nTo start the service:")
                    console.print(f"  systemctl --user enable comfyui-engine@1.service")
                    console.print(f"  systemctl --user start comfyui-engine@1.service")
            else:
                console.print("[yellow]Service template not found. Run install.sh manually.[/yellow]")

        except Exception as e:
            if console:
                console.print(f"[red]Failed to install systemd service: {e}[/red]")


class SummaryStep(WizardStep):
    """Display configuration summary and write files."""

    def __init__(self):
        super().__init__("Summary", "Configuration summary")

    async def run(self, config: EngineConfig) -> EngineConfig:
        if console:
            console.print(Panel("[bold]Configuration Summary[/bold]", border_style="green"))

            table = Table(show_header=True, header_style="bold")
            table.add_column("Setting")
            table.add_column("Value")

            # Group settings
            groups = {
                "Server": ["comfyui_host", "comfyui_port"],
                "Generation": ["default_width", "default_height", "default_steps", "default_cfg", "default_sampler"],
                "Performance": ["max_concurrent_jobs", "queue_poll_interval", "retry_attempts"],
                "Features": [
                    "mlflow_enabled",
                    "redis_enabled",
                    "metrics_enabled",
                    "websocket_enabled",
                    "checkpoint_enabled",
                ],
                "Output": ["output_dir", "git_enabled", "git_auto_commit"],
            }

            for group, keys in groups.items():
                table.add_row(f"[bold]{group}[/bold]", "")
                for key in keys:
                    value = getattr(config, key)
                    if isinstance(value, bool):
                        value = "✓ Enabled" if value else "✗ Disabled"
                    table.add_row(f"  {key}", str(value))
                table.add_row("", "")

            console.print(table)

            if Confirm.ask("\nSave configuration?", default=True):
                await self._write_config(config)
                console.print("[green]✓ Configuration saved![/green]")

            if Confirm.ask("Generate example prompts.yaml?", default=True):
                await self._generate_prompts(config)
                console.print("[green]✓ Example prompts generated![/green]")

        return config

    async def _write_config(self, config: EngineConfig) -> None:
        """Write configuration files."""
        # Write .env file
        env_path = Path(".env")
        env_path.write_text(config.to_env_file())

        # Write JSON config
        config_path = Path("config/engine.json")
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(config.to_json())

    async def _generate_prompts(self, config: EngineConfig) -> None:
        """Generate example prompts configuration."""
        prompts = {
            "categories": {
                "portraits": {
                    "templates": [
                        "portrait of {subject}, {style}, {lighting}, {quality}",
                        "professional headshot of {subject}, {background}, {quality}",
                    ],
                    "subjects": ["a young woman", "an elderly man", "a child", "a warrior"],
                    "styles": ["oil painting", "digital art", "photorealistic", "anime"],
                    "lighting": ["soft natural light", "dramatic studio lighting", "golden hour"],
                    "quality": ["highly detailed", "8k resolution", "masterpiece"],
                },
                "landscapes": {
                    "templates": [
                        "{type} landscape, {time}, {weather}, {quality}",
                        "panoramic view of {type}, {mood}, {quality}",
                    ],
                    "type": ["mountain", "ocean", "forest", "desert", "city"],
                    "time": ["sunrise", "sunset", "midday", "night"],
                    "weather": ["clear sky", "stormy", "foggy", "snowy"],
                    "mood": ["serene", "dramatic", "mysterious", "epic"],
                    "quality": ["highly detailed", "8k resolution", "masterpiece"],
                },
            },
            "loras": {
                "anime_style": {
                    "path": "models/loras/anime_style.safetensors",
                    "weight": 0.8,
                    "trigger": "anime style",
                },
                "photorealistic": {
                    "path": "models/loras/photorealistic.safetensors",
                    "weight": 0.6,
                    "trigger": "photorealistic",
                },
            },
            "defaults": {
                "width": config.default_width,
                "height": config.default_height,
                "steps": config.default_steps,
                "cfg_scale": config.default_cfg,
                "sampler": config.default_sampler,
            },
        }

        import yaml

        prompts_path = Path("config/prompts.yaml")
        prompts_path.parent.mkdir(parents=True, exist_ok=True)
        with open(prompts_path, "w") as f:
            yaml.dump(prompts, f, default_flow_style=False, sort_keys=False)


class SetupWizard:
    """Main setup wizard orchestrator."""

    def __init__(self, headless: bool = False, config_file: str | None = None):
        self.headless = headless
        self.config_file = config_file
        self.steps: list[WizardStep] = [
            WelcomeStep(),
            ServerConfigStep(),
            GenerationDefaultsStep(),
            PerformanceStep(),
            AdvancedFeaturesStep(),
            SystemdStep(),
            SummaryStep(),
        ]

    async def run(self) -> EngineConfig:
        """Run the complete wizard."""
        config = EngineConfig()

        # Load existing config if provided
        if self.config_file and Path(self.config_file).exists():
            with open(self.config_file) as f:
                data = json.load(f)
                for key, value in data.items():
                    if hasattr(config, key):
                        setattr(config, key, value)

        if self.headless:
            return await self._run_headless(config)

        # Interactive mode
        for step in self.steps:
            if console:
                console.print(f"\n[bold]Step: {step.name}[/bold] - {step.description}")
            config = await step.run(config)

        return config

    async def _run_headless(self, config: EngineConfig) -> EngineConfig:
        """Run in headless mode using environment variables."""
        # Override with environment variables
        for key in config.to_dict().keys():
            env_key = f"ENGINE_{key.upper()}"
            if env_key in os.environ:
                value = os.environ[env_key]
                # Type conversion
                if isinstance(getattr(config, key), bool):
                    value = value.lower() in ("true", "1", "yes", "on")
                elif isinstance(getattr(config, key), int):
                    value = int(value)
                elif isinstance(getattr(config, key), float):
                    value = float(value)
                setattr(config, key, value)

        # Write config files without interaction
        await SummaryStep()._write_config(config)

        if console:
            console.print("[green]Headless configuration complete.[/green]")

        return config


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="ComfyUI Engine Setup Wizard",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                          # Interactive setup
  %(prog)s --headless               # Use environment variables
  %(prog)s --config existing.json   # Load and modify existing config
  %(prog)s --validate               # Validate current configuration
        """,
    )
    parser.add_argument("--headless", action="store_true", help="Non-interactive mode")
    parser.add_argument("--config", help="Load existing configuration file")
    parser.add_argument("--validate", action="store_true", help="Validate current setup")
    parser.add_argument("--output", default=".env", help="Output configuration file")

    args = parser.parse_args()

    if args.validate:
        # Validate mode
        config = EngineConfig()
        if Path("config/engine.json").exists():
            with open("config/engine.json") as f:
                data = json.load(f)
                for key, value in data.items():
                    if hasattr(config, key):
                        setattr(config, key, value)

        # Run validation
        print(
            json.dumps(
                {
                    "valid": True,
                    "config": config.to_dict(),
                },
                indent=2,
            )
        )
        return

    # Run wizard
    wizard = SetupWizard(headless=args.headless, config_file=args.config)

    try:
        config = asyncio.run(wizard.run())

        if args.headless:
            print(f"Configuration written to {args.output}")

    except KeyboardInterrupt:
        if console:
            console.print("\n[yellow]Setup cancelled by user.[/yellow]")
        sys.exit(1)
    except Exception as e:
        if console:
            console.print(f"\n[red]Setup failed: {e}[/red]")
        sys.exit(1)


if __name__ == "__main__":
    main()
