"""
ComfyUI Async Generation Engine v4.0 - Type Stubs
Type safety improvements and protocol definitions.
"""

from typing import Any, Dict, List, Optional, Protocol, Tuple, runtime_checkable


@runtime_checkable
class EngineProtocol(Protocol):
    """Protocol for engine implementations."""

    async def health_check(self) -> bool: ...
    async def submit_job(self, job_data: Dict[str, Any]) -> str: ...
    async def get_job_status(self, job_id: str) -> Optional[Dict[str, Any]]: ...
    async def list_jobs(self, status: Optional[str], limit: int, offset: int) -> List[Dict[str, Any]]: ...
    async def cancel_job(self, job_id: str) -> bool: ...
    async def get_queue_status(self) -> Dict[str, Any]: ...
    async def pause_queue(self) -> None: ...
    async def resume_queue(self) -> None: ...
    async def get_metrics(self) -> Dict[str, Any]: ...
    async def get_prometheus_metrics(self) -> List[str]: ...
    async def shutdown(self) -> None: ...


@runtime_checkable
class MetricsProtocol(Protocol):
    """Protocol for metrics collectors."""

    async def inc(self, metric_name: str, value: int = 1) -> None: ...
    async def gauge(self, metric_name: str, value: float) -> None: ...
    async def observe(self, metric_name: str, value: float) -> None: ...
    async def histogram(self, metric_name: str, value: float) -> None: ...


@runtime_checkable
class QueueProtocol(Protocol):
    """Protocol for job queues."""

    async def enqueue(self, payload: Dict[str, Any], meta: Dict[str, Any], priority: int = 2, timeout: Optional[float] = None) -> Any: ...
    async def dequeue(self) -> Any: ...
    def qsize(self) -> int: ...
    def empty(self) -> bool: ...


@runtime_checkable
class StorageProtocol(Protocol):
    """Protocol for storage backends."""

    async def save(self, key: str, data: Dict[str, Any]) -> None: ...
    async def load(self, key: str) -> Optional[Dict[str, Any]]: ...
    async def delete(self, key: str) -> bool: ...
    async def list_keys(self, prefix: str = "") -> List[str]: ...


@runtime_checkable
class NotifierProtocol(Protocol):
    """Protocol for notification services."""

    async def send(self, message: str, level: str = "info", metadata: Optional[Dict[str, Any]] = None) -> bool: ...
    async def alert(self, message: str, metadata: Optional[Dict[str, Any]] = None) -> bool: ...


# Type aliases for common patterns
JobPayload = Dict[str, Any]
JobMeta = Dict[str, Any]
JobResult = Dict[str, Any]
WorkflowConfig = Dict[str, Any]
LoRAConfig = Dict[str, Any]
SamplingParams = Dict[str, Any]
Resolution = Tuple[int, int]
SeedValue = int
