apiVersion: v1
kind: ServiceAccount
metadata:
  name: comfyui-engine
  labels:
    app: comfyui-engine
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: comfyui-engine
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: comfyui-engine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: comfyui-engine
subjects:
- kind: ServiceAccount
  name: comfyui-engine
