{{- if .Values.persistence.models.enabled }}
---
{{- include "comfyui-engine.modelsPVC" . }}
{{- end }}

{{- if .Values.persistence.outputs.enabled }}
---
{{- include "comfyui-engine.outputsPVC" . }}
{{- end }}

{{- if .Values.persistence.cache.enabled }}
---
{{- include "comfyui-engine.cachePVC" . }}
{{- end }}
