apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comfyui-engine.secretName" . }}
  labels:
    {{- include "comfyui-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis.url: {{ .Values.secrets.redis.url | quote }}
  api.key.admin: {{ .Values.secrets.api.admin_key | quote }}
  api.key.readonly: {{ .Values.secrets.api.readonly_key | quote }}
