{{- if and .Values.secrets.jwt.enabled (not .Values.secrets.jwt.existingSecret) }}
{{- include "comfyui-engine.jwtSecret" . }}
{{- end }}
{{- if and .Values.secrets.db.enabled (not .Values.secrets.db.existingSecret) }}
---
{{- include "comfyui-engine.dbSecret" . }}
{{- end }}
