apiVersion: v1
kind: Service
metadata:
  name: {{ include "comfyui-engine.fullname" . }}
  labels:
    {{- include "comfyui-engine.labels" . | nindent 4 }}
    {{- include "comfyui-engine.extraLabels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- include "comfyui-engine.serviceAnnotations" . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "comfyui-engine.selectorLabels" . | nindent 4 }}
