{{- if .Values.monitoring.enabled -}}
{{- if .Values.monitoring.serviceMonitor.enabled -}}
{{- include "comfyui-engine.serviceMonitor" . }}
{{- end }}
{{- if .Values.monitoring.prometheusRule.enabled -}}
---
{{- include "comfyui-engine.prometheusRule" . }}
{{- end }}
{{- end }}
